#!/usr/bin/python

# What is the 10 001st prime number?

from math import sqrt

def isPrime(value):
	maxCandidate = int(sqrt(value))

	if(value % 2 == 0):
		return False

	for candidate in range(3, maxCandidate + 1, 2):
		if(value % candidate == 0):
			return False

	return True

def nth_prime(n):
	discoveredCount = 0
	candidate = 1
	lastDiscovered = -1
	
	while(discoveredCount < n):
		if(isPrime(candidate)):
			discoveredCount += 1
			lastDiscovered = candidate

		candidate += 2

	return lastDiscovered

if __name__ == "__main__":
	print nth_prime(10001)
