#!/usr/bin/python

# The sum of the squares of the first ten natural numbers is,
#		1**2 + 2**2 + ... + 10**2 = 385
# The square of the sum of the first ten natural numbers is,
#		(1 + 2 + ... + 10)**2 = 55**2 = 3025
#
# Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 - 385 = 2640.
# Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.

def sum_of_squares(value):
	_sum = 0
	
	for entry in range(1, value + 1):
	  _sum += entry**2

	return _sum

def square_of_sums(value):
  return value*value*(value+1)*(value+1) / 4

if __name__ == "__main__":
	value = 100
	print sum_of_squares(value) - square_of_sums(value)
