#!/usr/bin/python:q

# What is the 10 001st prime number?

from math import sqrt
from primes import is_prime

def nth_prime(n):
	discoveredCount = 0
	candidate = 1
	lastDiscovered = -1
	
	while(discoveredCount < n):
		if(is_prime(candidate)):
			discoveredCount += 1
			lastDiscovered = candidate

		candidate += 2

	return lastDiscovered

if __name__ == "__main__":
	print nth_prime(10001)
