#!/usr/bin/python

# this is more efficient to write, but runs slower since it iterates over the set of numbers twice -- once to filter and once to sum
numberSet = range(1, 1000)
multiples = filter(lambda x: x % 3 == 0 or x % 5 == 0, numberSet)
print sum(multiples)

# this was my first attempt, only requires iteration over the list once
total = 0
for value in range(1, 1000):
  if value % 3 == 0 or value % 5 == 0:
    total += value 

print total
