#!/usr/bin/python

# this is more efficient to write, but runs slower since it iterates over the set of numbers twice -- once to filter and once to sum
numberSet = range(1, 1000)
multiples = filter(lambda x: x % 3 == 0 or x % 5 == 0, numberSet)
print sum(multiples)

# this was my first attempt, only requires iteration over the list once
total = 0
for value in range(1, 1000):
  if value % 3 == 0 or value % 5 == 0:
    total += value 

print total

# this recognizes the mathematical properties of the problem
total = 0
max = 999
maxFor3 = 999 / 3
maxFor5 = 999 / 5
maxFor15 = 999 / 15

total += 3 * maxFor3 * (maxFor3 + 1)/2
total += 5 * maxFor5 * (maxFor5 + 1)/2
total -= 15 * maxFor15 * (maxFor15 + 1)/2
print total 
